### ISSUE TITLE
Add SSZ containers needed by P2P

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#171]
See: https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/native/ssz_nif/README.md

This should go in a different file other than `beacon_chain`

~**StatusMessage** (#187)~
```
(
  fork_digest: ForkDigest
  finalized_root: Root
  finalized_epoch: Epoch
  head_root: Root
  head_slot: Slot
)
```

**GoodbyeReason**
```
(
  uint64
)
```

~**BeaconBlocksByRangeRequest** (#190)~
```
(
  start_slot: Slot
  count: uint64
  step: uint64 # Deprecated, must be set to 1
)
```

~**BeaconBlocksByRangeResponse** (#190)~
```
(
  List[SignedBeaconBlock, MAX_REQUEST_BLOCKS]
)
```

**BeaconBlocksByRootRequest**
```
(
  List[Root, MAX_REQUEST_BLOCKS]
)
```

**BeaconBlocksByRootResponse**
```
(
  List[SignedBeaconBlock, MAX_REQUEST_BLOCKS]
)
```

**PingMessage**
```
(
  uint64
)
```

**MetaData** (#191)
```
(
  seq_number: uint64
  attnets: Bitvector[ATTESTATION_SUBNET_COUNT]
  syncnets: Bitvector[SYNC_COMMITTEE_SUBNET_COUNT]
)
```

**Comment by ayushm2003** [comment]
hey, I would like to take this up. Should the different messages be opened as separate issues?

**Comment by yash-atreya** [comment]
@MegaRedHand Implemented `BeaconBlocksByRootReq/Res` in PR #232

**Comment by MegaRedHand** [comment]
@ayushm2003 Since `GoodbyeReason` and `PingMessage` are containers with a single primitive field, it's easier to decode them from the Elixir side (the encoding is equal to the primitive type encoding). With #232 this issue will be complete.

@yash-atreya Thanks for implementing #232. That being said, please leave a message in the issue before starting work on it, to avoid duplicating work.

**Comment by mpaulucci** [comment]
This is being tackled in other issues. Closing
