### ISSUE TITLE
[operations] Implement `process_proposer_slashing`

### ISSUE THREAD

**Issue by phklive** [lambdaclass/lambda_ethereum_consensus#304]
https://github.com/lambdaclass/lambda_ethereum_consensus/blob/dd0a0523e6be2a21fa3f6a96d4466926307d236c/docs/specs/beacon-chain.md?plain=1#L2684-L2705

See Spec tests format: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/operations

Acceptance criteria:
- Run corresponding spec tests

**Comment by karasakalmt** [comment]
May I get this one as well since it is highly related with #301 I can implement it fast both uses `slash_validator` which I am implementing rn
<img width="1267" alt="Screenshot 2023-10-19 at 13 06 28" src="https://github.com/lambdaclass/lambda_ethereum_consensus/assets/32202283/eb2f9d38-2642-4294-98bb-0e0027dc3bfd">

**Comment by phklive** [comment]
Could you pr the one you have assigned first, then i will assign this one to you.

**Comment by karasakalmt** [comment]
I have done with the other one may I take this one>

**Comment by phklive** [comment]
> I have done with the other one may I take this one?

sure
