### ISSUE TITLE
Implement `rewards` spec test runner

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/lambda_ethereum_consensus#459]
Implement this spec test runner: https://github.com/ethereum/consensus-specs/tree/dev/tests/formats/rewards

**Comment by f3r10** [comment]
I think the specs about rewards are not updated. The functions mentioned can not be implemented because BeaconState container does not have `current_epoch_attestations` or `previous_epoch_attestations` fields on the Capella fork. 
I base the PR on https://github.com/michaelsproul/lighthouse/blob/unstable/testing/ef_tests/src/cases/rewards.rs

Moreover, in Capella `get_inclusion_delay_deltas` is not used anymore so the tests for that function are not implemented.

**Comment by mpaulucci** [comment]
Not sure I understand. What functions can't be implemented?

**Comment by MegaRedHand** [comment]
`get_inactivity_penalty_deltas` is still used. We can just ignore the rest of the functions if they're not implemented.

**Comment by f3r10** [comment]
According to the specs, it would be necessary to implement `get_source_deltas` `get_target_deltas` `get_head_deltas` `get_inclusion_delay_deltas` and   `get_inactivity_penalty_deltas` but these functions use  `current_epoch_attestations` and `previous_epoch_attestations` only defined on pre-Altair fork BeaconState container.

Instead for Capella, we have to test  `BeaconState.get_flag_index_deltas` for testing `source`,  `target`, and `head` flag weights along with  `get_inactivity_penalty_deltas`.  

The one that is not possible to test anymore for newer fork versions like Capella is `get_*inclusion*_delay_deltas`

**Comment by mpaulucci** [comment]
But lighthouse seems to compute all those deltas for post altair: https://github.com/sigp/lighthouse/blob/stable/testing/ef_tests/src/cases/rewards.rs#L129-L157

**Comment by f3r10** [comment]
yes!!, I did the same on my PR
